os: linux
arch: arm64
dist: bionic
sudo: required
language: python

notifications:
  email: false

python:
- "3.7"
- "3.8"
- "3.9"

before_install:
- sudo apt-get install -y libgdal-dev graphviz proj-bin gcc libproj-dev libspatialindex-dev

install:
- pip install -r requirements-dev.txt --upgrade
- FORCE_CYTHON=1 pip install cartopy  # temporal fix for cartopy==0.19.0
- if [ $TRAVIS_PYTHON_VERSION == '3.9' ]; then
    python install_all.py -e;
  else
    python install_all.py &&
    pip install ./io[METEOBLUE];
  fi

script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    sentinelhub.config --instance_id $INSTANCE_ID &&
    sentinelhub.config --sh_client_secret $SH_CLIENT_SECRET &&
    sentinelhub.config --sh_client_id $SH_CLIENT_ID ;
  fi
- if [ $TRAVIS_PYTHON_VERSION == '3.9' ]; then
    pylint core/eolearn/core/*.py &&
    pylint coregistration/eolearn/coregistration/*.py &&
    pylint features/eolearn/features/*.py &&
    pylint geometry/eolearn/geometry/*.py &&
    pylint io/eolearn/io/*.py &&
    pylint mask/eolearn/mask/*.py &&
    pylint ml_tools/eolearn/ml_tools/*.py &&
    pylint visualization/eolearn/visualization/*.py;
  fi
- >
  if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    if [ $TRAVIS_PYTHON_VERSION == '3.9' ]; then
      pytest -c=.coveragerc;
    else
      pytest;
    fi;
  else
    pytest \
      --ignore io/eolearn/tests/test_sentinelhub_process.py ;
  fi
# - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then pytest --nbval-lax examples/visualization/EOPatchVisualization.ipynb  ; fi'

after_success:
- if [ $TRAVIS_PYTHON_VERSION == '3.9' ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then codecov; fi
