name: eo-learn-docs
channels:
- conda-forge
dependencies:
- rasterio
- pip:
  - Sphinx~=4.0
  - sphinx_rtd_theme>=1.0.0
  - nbsphinx
  - jupyter
  - m2r2

  - ./../core
  - ./../coregistration
  - ./../features
  - ./../geometry
  - ./../io[METEOBLUE]
  - ./../mask
  - ./../ml_tools
  - ./../visualization
